### ISSUE TITLE
Serialized needs to be ignored by git

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#100]
@Tanner However you do your magic, make it so we don't overwrite our save games when we pull.  kthxbai

**Comment by Tanner** [comment]
Is it the resources/serialized/game.ser file?

**Comment by Irdakuh** [comment]
yes, but i want the whole folder to be ignored, if that's possible

**Comment by Tanner** [comment]
Fixed by 3481de5c05ea1aec745baca988b718f81b25b3da.
