### ISSUE TITLE
Load Dialog with No Saves

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#109]
If there are no saves in resources/serialized, it should not allow "OK" to be pressed.

Otherwise you get a:
java.io.FileNotFoundException: resources/serialized/Game 1.ser (No such file or directory)

**Comment by Irdakuh** [comment]
Are you doing this from sceneSelectorScene?  because main menu shouldn't even let you press the load button and bring up the modal.

**Comment by Tanner** [comment]
Yep. Just started the app, let it load, press "Load" and then "OK".

**Comment by Irdakuh** [comment]
I cannot reproduce this error

**Comment by Tanner** [comment]
Hrm. In my resources directory I have a serialized folder with a game.ser in it. Nothing else.

When I bring up the "Load Modal" I get: http://cl.ly/2i2w0u1439393k1x4313

If I delete the serialized directory, the Load button is disabled. If I create an empty serialized directory, the Load button is disabled. If I put a *.ser file in there, the Load button is active and I can click on "OK". Suspecting it thinks the right file is there, but doesn't realize its not according to the Load modal's specifications of "Game #".

**Comment by Irdakuh** [comment]
ah.  so what you're saying is, you're being mean and breaking the system.  Mean Tanner is mean.  Do we really need to do handling for if the user goes into their save files and changes/removes things?  The save button will handle adding your save files for you - you should never have to touch it.

**Comment by Tanner** [comment]
I'm not going into the save files, I just added a file in that directory that the game didn't put there.

**Comment by Irdakuh** [comment]
That's my point.  you've gone into the save folder and modified stuff.  Dont do that.  But I can check against it if I must.
