### ISSUE TITLE
Load button doesn't reactivate after saving from mainMenuScene

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#110]
All we need is something to let mainMenuScene know when it's been gone into from another scene, if that's at all possible.  Or just make options' save method not possible from mainMenuScene.  Either way.

**Comment by Tanner** [comment]
Maybe we should make it so when you go to MainMenuScene from any other Scene (other than Loader), it automatically saves the game at where you were? MainMenuScene shouldn't have a Save button.

**Comment by Irdakuh** [comment]
Autosaving?  I don't like that...what if something bad happened and I wanted to go back and reload?  The problem is fixed by either disabling the options screen's save from mainMenu, or just not giving main menu an options screen.  the only thing it needs from options is the sound control, and we could replace the current options button with that.

**Comment by tgrenbergj** [comment]
You can just implement the enter method, then every time it enters the scene it should recheck the save files.  I believe this works.
