### ISSUE TITLE
died of starvation with 99 meat in the wagon

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#112]
the meat on the top of the stack had 0 condition though.  apparently it wasn't popped off.  hard to reproduce although it would probably make a great junit test case.

**Comment by Irdakuh** [comment]
Interesting.  I wonder if it was actually that, or if you were running on grueling pace/barebones rations, because that will exhaust you to death even if you have food.  I'll try to reproduce.
