### ISSUE TITLE
Store Issue

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#113]
During the demo, when I had $4 left, I tried to buy some apples, but for some reason the game wasn't doing anything - it wasn't subtracting the money or giving me any apples. I did it several times during the demo and it never worked. Not sure if anyone caught that.

**Comment by tgrenbergj** [comment]
Confirmed.  If you have exactly the amount of money as the item you are trying to buy, it will look like it lets you buy the item, but your money does not decrease, nor does the item get added to the inventory.  I will fix this.

**Comment by Irdakuh** [comment]
I saw that too.  Very sneaky getting out of there, btw
