### ISSUE TITLE
whoa nellie

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#116]
can we slow down time in the town scene?  like...by a factor of 1000?  as it is it takes 3 hours to walk to the store.   would be sweet if this wasn't happening for our demo tomorrow.

**Comment by Irdakuh** [comment]
demo tomorrow? and we've already discussed making this happen

**Comment by jturner65** [comment]
aren't we demoing in class tomorrow?   and sorry, i'm old and miss things.

**Comment by Irdakuh** [comment]
OOOH, that one
