### ISSUE TITLE
map relies on ability to generate a 0 condition.

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#124]
i guess i can change this in the map code, if we want it to be impossible to have min = max in a condition, but up until tonight this was allowed and it means stopping this from happening might break other things too.

i've changed it to just check if max is less than min, instead of les than or equal, but if we want it to be that way then we need to prepare to wade through some gore :).

i did not change the junit test for condition, so it is testing to make sure that min is always < max currently.

on that note, we also did not submit any exception handling strategy, so i think it's a bad idea to throw exceptions now - point loss imminent, i would think.  instead of throwing an exception in condition, if we want to force values to be within a particular range we should just force edge cases to be legal, and let whoever consumes the methods in question deal with the results.

**Comment by ryanashcraft** [comment]
I disagree, John. We did have an exception handle strategy, and we said that we would throw Java exceptions, just not make our own.

This is a perfect example of when you want a Runtime exception to be thrown. If there's ever a bug with the app because someone mixed up the ordering of the parameters, we would have no idea how to debug it if this exception wasn't thrown.

I made a mistake by throwing an exception if min == max, and I have fixed that.

**Comment by Tanner** [comment]
If min is max, then why are you using a Condition and not a boolean?

**Comment by jturner65** [comment]
ok, ryan.  i must be mis-remembering our meeting with aurel on this topic - i could have sworn that we didn't design into our project any explicit strategy and we told him that was because we were not going to have any game related player i/o that  could cause exceptions outside of naming their characters. 

as for it being a good spot for an exception to be thrown, i certainly agree - i just didn't want the inclusion of exception handling, this late, to cause an issue.

tanner,  it isn't necessarily that the value is min=max, it's that a 0 condition might be made, on occasion, as a consequence of the generated map code, and this causes the condition to then build itself as (0,0,0). this in turn is because a map object is required to exist in some instances before everything that determines what its condition might be exists, and so a "place holder" might be required.
