### ISSUE TITLE
how do we tile a graphic in a panel?

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#126]
trying to tile a background, doesn't seem to work - is there something i need to tell it to tile or do i need to do it manually?  thanks.

**Comment by Tanner** [comment]
Tiling was never implement.

You'd have to do it manually with add as grid or something along those lines.

**Comment by jturner65** [comment]
i am disappoint. :(

i'll look into the add as grid - thanks man :).

all i need to figure out now is how to make the object properly that i'm using to hold all this stuff (And what object i should use for it - panel? not sure).

**Comment by Tanner** [comment]
Ryan says Slick has something, but he couldn't understand it. Perhaps you can.

**Comment by Tanner** [comment]
A Panel that holds sprites/image makes sense. That's what a ParallaxPanel is. You probably don't have to subclass though.

**Comment by jturner65** [comment]
the issue i'm having is there's a -massive- performance hit when i try to make a component to hold each of the sprites.  i need a single component to hold all the sprites, but when i was trying to make this i was getting all the sprites put on top of each other, despite that i was offsetting them, and expanded to the size of the screen.  i'll go back to it in a bit, finishing up implementing everything else i can now.

**Comment by Tanner** [comment]
What are you expanding to the size of the screen? As far as I know, it should be like you have a giant panel (size of screen) that holds all of the images in a grid.
