### ISSUE TITLE
can we set the png loader to accept 8 bit pngs?

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#128]
don't know where this is going on - as it is now it only accepts 32 bit pngs, which is massive overkill for a lot of my graphics.  since the huntscene requires a lot of images, i'm trying to make them as small as possible, and cutting down from 32 to 8 garners me a 50-75% savings in space on very large graphics, more on smaller ones.

**Comment by Tanner** [comment]
A google says it should work. I think.

**Comment by jturner65** [comment]
it would really help, i think, athough right now, i have the images tuned somewhat and they're not tooo too bad.  still, i'd like em to be smaller if possible.
