### ISSUE TITLE
can someone make me a hunt modal?

### ISSUE THREAD

**Issue by jturner65** [Tanner/Oregon-Trail#129]
if the player has no gun in their inventory i'd rather not let them enter the hunt scene.  if someone could give me a modal out of camp to handle this, i'd appreciate it :D.

**Comment by Tanner** [comment]
A message modal isn't too hard to create. Look at the modals presented from the encounters or in RiverScene.

**Comment by jturner65** [comment]
yeah, i didn't think it would be too hard.  i was just figuring if somebody wasn't working on anything they could help me out.  still have a lot of stuff to figure out with the huntscene.
