### ISSUE TITLE
Handle various cases in StoreScene (aka no wagon, first wagon, etc) and make smarter Modal messages

### ISSUE THREAD

**Issue by tgrenbergj** [Tanner/Oregon-Trail#28]
Scene needs to check if the party has no wagon, and only allow the purchase of a single wagon if they have none to begin with.  Create modal messages that reflect this.

Also, "Can't buy" messages are very boring.  Need to create modals that say "You are over-encumbered," or "You don't have enough money."

**Comment by Irdakuh** [comment]
I can write a method in party that you can call if canGetItems returns null that will return a String with a message based on why it failed, if you would like that.  Might make your life easier.
