### ISSUE TITLE
Need timer function triggering from TrailScene

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#32]
I would like a trail scene with at least a timer to trigger every few seconds or so.  I'm pretty sure if I had that, we could have FS3 knocked out pretty easily.  Let me know whoever wants to make it.

**Comment by Tanner** [comment]
Which timer is this?

**Comment by Irdakuh** [comment]
Whatever one we're going to use to make trail scene progress through the steps.  It's the one that'll trigger the party numbers to update each step forward on the trail.

**Comment by Tanner** [comment]
Not sure which one that would be, but would probably be the in-game time with a delta.

**Comment by Irdakuh** [comment]
Yeah, pretty much.  It's just whatever we're going to use in game to make the trail scene say "ok, they've had enough time to click buttons to pause, I'm advancing"
