### ISSUE TITLE
Request: Scene from which I can test inventory food-eating functionality.

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#36]
Needs to have:
1.  Person and Wagon, with inventory and health displays (or at least labels that I can work with)
2.  Button to click to walk forward.
3. Rations/Pace segmented control.
4.  Ability to add items to an inventory (just a small infinite store scene would do).

Jeremy, you asked for tasks.  I've got you one.

This does not need to be fancy.  Just functional.

**Comment by Tanner** [comment]
Number 1 should be a HUD view class kinda like modal is. Kinda. I'd work on that, but I need to finish PIS first.

**Comment by Irdakuh** [comment]
yeah, but this was just a test screen.  i talked to jeremy, and i just want a mod to pis for testing

**Comment by Tanner** [comment]
What?

**Comment by Irdakuh** [comment]
Don't worry, Jeremy knows what i want

**Comment by Irdakuh** [comment]
Yay! Guys, you should test this out, just to see if you can find improvements/things I should take into account.  Go into devMode, add a party, and then go to trailTestScene.  Set the rations/pace however you want, click update P/R, then click walk.  The party health bars should all go to the same percentage (ish) (which is a feature, don't worry that it's not exact, it's not meant to be), and their foodstuffs should change (if it doesn't the first time, try stepping a few more.  you can live a long time on a loaf of bread).  currently death isn't taken into account, and location isn't displayed, but that is an easy fix.
