### ISSUE TITLE
Store Scene doesn't update store inventory/price when returning from PIS

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#39]
After selling items to the store from PIS, the store scene does not update quantities or the party's current money. The logs reflect this.

Probably a @tgrenbergj thing. Should probably use start() method from scene (be sure to call super).

**Comment by Irdakuh** [comment]
Is this a 'does not update' error or a 'does not reflect changes' error?  Meaning, is it simply that store scene needs to call refresh, or that the numbers are legitimately not right?

**Comment by Tanner** [comment]
The numbers in the log are correct, the store just doesn't reflect the changes.
