### ISSUE TITLE
Multiple Item Selection

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#52]
Allow for the possibility during store scene (and maybe PIS) for the player to type in a number (strictly regulated, of course) to set how many of an item they want to take off a stack.  (i.e., they want 50 apples from the store, but dont want to click 50 times)

**Comment by jturner65** [comment]
i think a better idea would be using a "ctl + click" combo to decrement/increment by 10 instead of 1.  keyboard input is bad, mmkay - messy, potential errors.
