### ISSUE TITLE
Use SoundStore singleton from Slick API

### ISSUE THREAD

**Issue by ryanashcraft** [Tanner/Oregon-Trail#57]
Instead of going through GameDirector to play music.

**Comment by Irdakuh** [comment]
I don't like SoundStore.  I might just write my own singleton that handles this instead

**Comment by ryanashcraft** [comment]
Why not?

Sent from my iPhone

On Oct 25, 2011, at 3:12 PM, hankrearden
reply@reply.github.com
wrote:

**Comment by Irdakuh** [comment]
It doesn't give me the flexibility I want.  I see no way to have it store sounds, or to be able to get a list of possible sounds I could use out of it.  I just think I could write something that would better suit our needs.

**Comment by ryanashcraft** [comment]
Make a sound manager that uses sound store then. Sound good? Similar
to font manager?

Sent from my iPhone

On Oct 25, 2011, at 3:42 PM, hankrearden
reply@reply.github.com
wrote:

**Comment by Irdakuh** [comment]
Created my own sound store.  Doesn't use SoundStore at all...it works just like sharedDirector - scenes can call methods like "Play this sound" or "Play this music" or "Stop that music".

**Comment by ryanashcraft** [comment]
What about mute? I think there's a reason why slick made this class
available. Could be caching or loading efficiently. Please do research
and consider options.

Sent from my iPhone

On Oct 25, 2011, at 5:28 PM, hankrearden
reply@reply.github.com
wrote:

**Comment by Irdakuh** [comment]
What I'm saying is, my class can offer all the functionality of SoundStore, and has a better interface with the code.  As for caching and loading, soundStore will take just as long.  The loading time is because it has to actually read the files and convert them to something useable.  I tried using soundStore, and it just didn't let me do what I wanted.

**Comment by ryanashcraft** [comment]
Ok as long as you've compared yours with theirs and the results are
the same I'm ok. Mute is an option, correct?

Sent from my iPhone

On Oct 25, 2011, at 5:47 PM, hankrearden
reply@reply.github.com
wrote:

**Comment by Irdakuh** [comment]
yes, I've added mute as an option.  I don't think they do anything I can't, and if they do, I'll fix mine so that I do too.

**Comment by ryanashcraft** [comment]
Good George. :) Now make font manager also a singleton.

Sent from my iPhone

On Oct 25, 2011, at 6:05 PM, hankrearden
reply@reply.github.com
wrote:
