### ISSUE TITLE
Trail Choice Modal Duplicates

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#65]
It shows trails that either have the same name or have the same city name but in a different territory.

http://cl.ly/34373h1g442D400r1O0d

@hankrearden or @jturner65

**Comment by Irdakuh** [comment]
Currently this occurs because of a lack of names available for loading, and because the generator isn't the smartest.  I believe John to be working on this

**Comment by jturner65** [comment]
same name different territory isn't an issue - that was common at that time (and still is common - look up how many kansas cities there are in various states, or philadelphias.

still, the intention is to make things as diverse as possible, so yes, this is being worked on.

**Comment by Tanner** [comment]
Closing this issue in favor of #68.
