### ISSUE TITLE
Trail Choice Modal needs a way to differentiate the trails

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#68]
The trail choice options should tell what direction the trail goes, how long it is, and/or how difficult it is.

**Comment by Irdakuh** [comment]
There will be a rough directional approximation and a difficulty rating.  I just haven't gotten around to implementing it yet.

**Comment by Irdakuh** [comment]
@jturner65 Any chance I could get a rough approximation of direction (i.e., N, NW, W, SW, S)
