### ISSUE TITLE
Condition refactor

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#69]
I've come upon a situation where it would be beneficial to me to have all the integers in condition changed to doubles.  I'm willing to do this refactor, and I just wanted to make sure nobody had any issues with this/code depending on this before I did.  All this will do is allow our conditions to me more precise.  Bottoming out and maxing out will still work as they do currently.  Let me know with a yea/nay.

**Comment by Tanner** [comment]
Sounds fine to me. Curious though what the situation is?

**Comment by Irdakuh** [comment]
I'm nerfing the distance you travel each step down to quite low, and I want modifiers to mean something, so now, even though I'll only tell you you've gone X miles, you've really gone X.XX miles.  I'm currently doing this, but very, VERY hackily (read party.walk() and you'll see...).  And besides, there's really no reason not to be using doubles, at least that I can see.
