### ISSUE TITLE
Button sounds don't always work

### ISSUE THREAD

**Issue by Tanner** [Tanner/Oregon-Trail#74]
Sound "clicks" for the Button don't work in Store Scene, Town Scene, or the Modals.

It should work for all buttons…

**Comment by Irdakuh** [comment]
I suggest we make a change to the way the sound is handled.  Have all buttons have a sound, and then do something with the listener/functionality of said listener such that whenever a button is clicked, it plays the sound.  I didn't know how to do this/what would be best implementation.

**Comment by Irdakuh** [comment]
Do you want to handle this?  I can force these things to do it, but I think we could do it better that just 'remember to click your buttons, folks'

**Comment by Tanner** [comment]
Yeah. I'm working on it.

**Comment by Tanner** [comment]
Fixed in 522ce33d3b9da4f2513692d2cb8bdb77d7c1b3a4 and 51d5393c3bb6c71429b59f2cfdd4bd162ab2cb71.
