### ISSUE TITLE
Problem in worldMap

### ISSUE THREAD

**Issue by Irdakuh** [Tanner/Oregon-Trail#77]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 80
    at scene.MapScene.init(MapScene.java:52)

Go into sceneSelectorScene.  Reset party, go to map, works fine.  Now go back to sceneSelector, reset game, reset party, crash.  Seems to be some flaw during:
this.worldMap = new WorldMap(); in game.reset()

Thats all i can think of - that something isn't being called right, or worldmap just really, really doesn't want to be reset.

**Comment by Irdakuh** [comment]
Found the problem.  @jturner65 will need to implement node ID through worldMap, not LocationNode.

/*\* class-wide counter of nodes */
    private static int nodeCount;

public LocationNode(String locationName, int xPos, int yPos, double latitude, double longitude, int trails, int rank, int quality){
        this.ID = LocationNode.nodeCount++; //RIGHT HERE
        //until we can get a nice source for lat and long data
        MAP_XPOS = xPos;

ID should be passed in as a parameter, not read out of a static variable.

**Comment by jturner65** [comment]
Yeah I saw this as I was coding.  It's caused, as far as i could tell, by the hard reset of the game not completely feasting everything. This begs the question-will such a reset be available to the player in the game?

**Comment by jturner65** [comment]
Feasting?  LOL @ phone.  I meant resetting.

**Comment by Irdakuh** [comment]
Why was this closed?  This could happen in real game (player starts playing, quits, creates a new game).  I can write a workaround/fix if you guys want.  @jturner65

**Comment by Tanner** [comment]
Err… I have no idea why this was closed…

In my opinion, the player should be able to get to the main menu and create a new game at any time.

**Comment by jturner65** [comment]
this should have been addressed.  if it still is an issue, reopen.
